### PR TITLE
Fix the import error by falling back to earlier sanic versions

### LINKED ISSUE #12: import sanic.server.CIMultiDict
api.py still imports CIMultiDict from sanic.server

### PR DESCRIPTION
**Pull request by MihaiBalint**
Fixes the broken import following the import pattern applied here: https://github.com/ashleysommer/sanic-cors/commit/187726f81493dc0d2974bc67597cb9786324c02b

Also fixes #12

### CODE REVIEW

**Comment by ashleysommer** [comment]
Thanks!
Do you need a new pypi release with this fix?

**Comment by nimoism** [comment]
Yes, please, because last version in pypi is broken for me and it enforces me to use old sanic version
Thank you much!

**Comment by ashleysommer** [comment]
Done. See v0.3.5.post1 on pypi

**Comment by ashleysommer** [comment]
@MihaiBalint @nimoism 

I've spent a few hours pulling in from Flask-Restplus all of the changes from the last 18 months, since when I last rebased this port.

I've released the resulting Sanic-Restplus as v0.4.0b1 for testing.
There are not as many changes as I thought, some of them are very small, but others like Unordered vs Ordered schemas, Authorization and Security doc properties, and enhanced error handling have resulted larger diffs.

So if you want to, can you guys test the v0.4.0b1 release on your applications to see if everything works for you.

**Pull request merged**
