### PR TITLE
fix "from sanic.response import STATUS_CODES" in sanic v20+

### LINKED ISSUE #20: Error import STATUS_CODES in sanic 20+
```
from sanic.response import STATUS_CODES as ALL_STATUS_CODES
ImportError: cannot import name 'STATUS_CODES'
```

It seems that the STATUS_CODES is removed from sanic.response in sanic v20+ in a cleanup commit.
It's better to use the origin codes in sanic.helper directly.

### PR DESCRIPTION
**Pull request by tc-imba**
fix #20

### CODE REVIEW

**Comment by stikks** [comment]
Any idea when this PR will get merged? It's been open for a couple of months now and it breaks the use of `sanic-restplus` with sanic >-= 20.0

**Comment by ashleysommer** [comment]
Hi. Sorry, I thought I merged this PR months ago.
Merging now.
Its weird, I am using sanic-restplus on sanic 20.9 without any problem on two production deployments.

**Comment by stikks** [comment]
> Hi. Sorry, I thought I merged this PR months ago.
> Merging now.
> Its weird, I am using sanic-restplus on sanic 20.9 without any problem on two production deployments.

Sweet, thanks for merging. I was using it with sanic 20.12

**Comment by ashleysommer** [comment]
Ok. Sanic 20.12 was only released a couple of days ago. I have not done any testing of any of my Sanic plugins against Sanic 20.12 yet (will start soon though).

**Comment by stikks** [comment]
> Ok. Sanic 20.12 was only released a couple of days ago. I have not done any testing of any of my Sanic plugins against Sanic 20.12 yet (will start soon though).

oh I see. Thanks for merging this. I'm assuming the changes will be available in the next release

**Comment by ashleysommer** [comment]
Hi @stikks 
Yes, this change is now released as part of v0.5.5

**Pull request merged**
